### ISSUE TITLE
flatpak/appimage 打包

### ISSUE THREAD

**Issue by msojocs** [msojocs/deepin-music-pkg#1]
- [x] msojocs/deepin-music-pkg#4
- [x] msojocs/deepin-music-pkg#2
- [x] msojocs/deepin-music-pkg#3

**Comment by msojocs** [comment]
https://github.com/linuxdeepin/open-source-students/issues/10

**Comment by msojocs** [comment]
运行添加音乐崩溃，但理论上不影响打包

后续
---
不兼容ffmpeg4以上，已使用脚本修正
